#!/bin/sh

#clean up
rm -rf obj_dir
rm -f  sinewave.vcd

#run Verilator to translate verilog into c++, including c++ testbench
verilator -Wall --cc --trace sinegen.sv --exe sinegen_tb.cpp
# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vsinegen.mk Vsinegen
# run executable simulation file
obj_dir/Vsinegen
